
// Extender functions
	"/// Get a read-only LuaValueList containing this ViewFrame." "\r\n"
	"import LuaValueList* AsLuaValue(this ViewFrame*);" "\r\n"
	"/// Attempt to call a custom Lua method attached to this ViewFrame." "\r\n"
	"import LuaValueList* LuaMethod(this ViewFrame*, String methodName, LuaValueList* params = 0, LuaCallMode = eLuaUnprotectedMode);" "\r\n"
	"/// Get a read-only LuaValueList containing this DrawingSurface." "\r\n"
	"import LuaValueList* AsLuaValue(this DrawingSurface*);" "\r\n"
	"/// Attempt to call a custom Lua method attached to this DrawingSurface." "\r\n"
	"import LuaValueList* LuaMethod(this DrawingSurface*, String methodName, LuaValueList* params = 0, LuaCallMode = eLuaUnprotectedMode);" "\r\n"
	"/// Get a read-only LuaValueList containing this File." "\r\n"
	"import LuaValueList* AsLuaValue(this File*);" "\r\n"
	"/// Attempt to call a custom Lua method attached to this File." "\r\n"
	"import LuaValueList* LuaMethod(this File*, String methodName, LuaValueList* params = 0, LuaCallMode = eLuaUnprotectedMode);" "\r\n"
	"/// Get a read-only LuaValueList containing this InventoryItem." "\r\n"
	"import LuaValueList* AsLuaValue(this InventoryItem*);" "\r\n"
	"/// Attempt to call a custom Lua method attached to this InventoryItem." "\r\n"
	"import LuaValueList* LuaMethod(this InventoryItem*, String methodName, LuaValueList* params = 0, LuaCallMode = eLuaUnprotectedMode);" "\r\n"
	"/// Get the value of a custom Lua field attached to this InventoryItem." "\r\n"
	"import LuaValueList* GetLuaField(this InventoryItem*, String fieldName);" "\r\n"
	"/// Set the value of a custom Lua field attached to this InventoryItem." "\r\n"
	"import void SetLuaField(this InventoryItem*, String fieldName, LuaValueList* newValue);" "\r\n"
	"/// Get a read-only LuaValueList containing this Overlay." "\r\n"
	"import LuaValueList* AsLuaValue(this Overlay*);" "\r\n"
	"/// Attempt to call a custom Lua method attached to this Overlay." "\r\n"
	"import LuaValueList* LuaMethod(this Overlay*, String methodName, LuaValueList* params = 0, LuaCallMode = eLuaUnprotectedMode);" "\r\n"
	"/// Get a read-only LuaValueList containing this DynamicSprite." "\r\n"
	"import LuaValueList* AsLuaValue(this DynamicSprite*);" "\r\n"
	"/// Attempt to call a custom Lua method attached to this DynamicSprite." "\r\n"
	"import LuaValueList* LuaMethod(this DynamicSprite*, String methodName, LuaValueList* params = 0, LuaCallMode = eLuaUnprotectedMode);" "\r\n"
	"/// Get a read-only LuaValueList containing this GUIControl." "\r\n"
	"import LuaValueList* AsLuaValue(this GUIControl*);" "\r\n"
	"/// Attempt to call a custom Lua method attached to this GUIControl." "\r\n"
	"import LuaValueList* LuaMethod(this GUIControl*, String methodName, LuaValueList* params = 0, LuaCallMode = eLuaUnprotectedMode);" "\r\n"
	"/// Get the value of a custom Lua field attached to this GUIControl." "\r\n"
	"import LuaValueList* GetLuaField(this GUIControl*, String fieldName);" "\r\n"
	"/// Set the value of a custom Lua field attached to this GUIControl." "\r\n"
	"import void SetLuaField(this GUIControl*, String fieldName, LuaValueList* newValue);" "\r\n"
	"/// Get a read-only LuaValueList containing this Label." "\r\n"
	"import LuaValueList* AsLuaValue(this Label*);" "\r\n"
	"/// Attempt to call a custom Lua method attached to this Label." "\r\n"
	"import LuaValueList* LuaMethod(this Label*, String methodName, LuaValueList* params = 0, LuaCallMode = eLuaUnprotectedMode);" "\r\n"
	"/// Get the value of a custom Lua field attached to this Label." "\r\n"
	"import LuaValueList* GetLuaField(this Label*, String fieldName);" "\r\n"
	"/// Set the value of a custom Lua field attached to this Label." "\r\n"
	"import void SetLuaField(this Label*, String fieldName, LuaValueList* newValue);" "\r\n"
	"/// Get a read-only LuaValueList containing this Button." "\r\n"
	"import LuaValueList* AsLuaValue(this Button*);" "\r\n"
	"/// Attempt to call a custom Lua method attached to this Button." "\r\n"
	"import LuaValueList* LuaMethod(this Button*, String methodName, LuaValueList* params = 0, LuaCallMode = eLuaUnprotectedMode);" "\r\n"
	"/// Get the value of a custom Lua field attached to this Button." "\r\n"
	"import LuaValueList* GetLuaField(this Button*, String fieldName);" "\r\n"
	"/// Set the value of a custom Lua field attached to this Button." "\r\n"
	"import void SetLuaField(this Button*, String fieldName, LuaValueList* newValue);" "\r\n"
	"/// Get a read-only LuaValueList containing this Slider." "\r\n"
	"import LuaValueList* AsLuaValue(this Slider*);" "\r\n"
	"/// Attempt to call a custom Lua method attached to this Slider." "\r\n"
	"import LuaValueList* LuaMethod(this Slider*, String methodName, LuaValueList* params = 0, LuaCallMode = eLuaUnprotectedMode);" "\r\n"
	"/// Get the value of a custom Lua field attached to this Slider." "\r\n"
	"import LuaValueList* GetLuaField(this Slider*, String fieldName);" "\r\n"
	"/// Set the value of a custom Lua field attached to this Slider." "\r\n"
	"import void SetLuaField(this Slider*, String fieldName, LuaValueList* newValue);" "\r\n"
	"/// Get a read-only LuaValueList containing this TextBox." "\r\n"
	"import LuaValueList* AsLuaValue(this TextBox*);" "\r\n"
	"/// Attempt to call a custom Lua method attached to this TextBox." "\r\n"
	"import LuaValueList* LuaMethod(this TextBox*, String methodName, LuaValueList* params = 0, LuaCallMode = eLuaUnprotectedMode);" "\r\n"
	"/// Get the value of a custom Lua field attached to this TextBox." "\r\n"
	"import LuaValueList* GetLuaField(this TextBox*, String fieldName);" "\r\n"
	"/// Set the value of a custom Lua field attached to this TextBox." "\r\n"
	"import void SetLuaField(this TextBox*, String fieldName, LuaValueList* newValue);" "\r\n"
	"/// Get a read-only LuaValueList containing this InvWindow." "\r\n"
	"import LuaValueList* AsLuaValue(this InvWindow*);" "\r\n"
	"/// Attempt to call a custom Lua method attached to this InvWindow." "\r\n"
	"import LuaValueList* LuaMethod(this InvWindow*, String methodName, LuaValueList* params = 0, LuaCallMode = eLuaUnprotectedMode);" "\r\n"
	"/// Get the value of a custom Lua field attached to this InvWindow." "\r\n"
	"import LuaValueList* GetLuaField(this InvWindow*, String fieldName);" "\r\n"
	"/// Set the value of a custom Lua field attached to this InvWindow." "\r\n"
	"import void SetLuaField(this InvWindow*, String fieldName, LuaValueList* newValue);" "\r\n"
	"/// Get a read-only LuaValueList containing this ListBox." "\r\n"
	"import LuaValueList* AsLuaValue(this ListBox*);" "\r\n"
	"/// Attempt to call a custom Lua method attached to this ListBox." "\r\n"
	"import LuaValueList* LuaMethod(this ListBox*, String methodName, LuaValueList* params = 0, LuaCallMode = eLuaUnprotectedMode);" "\r\n"
	"/// Get the value of a custom Lua field attached to this ListBox." "\r\n"
	"import LuaValueList* GetLuaField(this ListBox*, String fieldName);" "\r\n"
	"/// Set the value of a custom Lua field attached to this ListBox." "\r\n"
	"import void SetLuaField(this ListBox*, String fieldName, LuaValueList* newValue);" "\r\n"
	"/// Get a read-only LuaValueList containing this GUI." "\r\n"
	"import LuaValueList* AsLuaValue(this GUI*);" "\r\n"
	"/// Attempt to call a custom Lua method attached to this GUI." "\r\n"
	"import LuaValueList* LuaMethod(this GUI*, String methodName, LuaValueList* params = 0, LuaCallMode = eLuaUnprotectedMode);" "\r\n"
	"/// Get the value of a custom Lua field attached to this GUI." "\r\n"
	"import LuaValueList* GetLuaField(this GUI*, String fieldName);" "\r\n"
	"/// Set the value of a custom Lua field attached to this GUI." "\r\n"
	"import void SetLuaField(this GUI*, String fieldName, LuaValueList* newValue);" "\r\n"
	"/// Get a read-only LuaValueList containing this Hotspot." "\r\n"
	"import LuaValueList* AsLuaValue(this Hotspot*);" "\r\n"
	"/// Attempt to call a custom Lua method attached to this Hotspot." "\r\n"
	"import LuaValueList* LuaMethod(this Hotspot*, String methodName, LuaValueList* params = 0, LuaCallMode = eLuaUnprotectedMode);" "\r\n"
	"/// Get the value of a custom Lua field attached to this Hotspot." "\r\n"
	"import LuaValueList* GetLuaField(this Hotspot*, String fieldName);" "\r\n"
	"/// Set the value of a custom Lua field attached to this Hotspot." "\r\n"
	"import void SetLuaField(this Hotspot*, String fieldName, LuaValueList* newValue);" "\r\n"
	"/// Get a read-only LuaValueList containing this Region." "\r\n"
	"import LuaValueList* AsLuaValue(this Region*);" "\r\n"
	"/// Attempt to call a custom Lua method attached to this Region." "\r\n"
	"import LuaValueList* LuaMethod(this Region*, String methodName, LuaValueList* params = 0, LuaCallMode = eLuaUnprotectedMode);" "\r\n"
	"/// Get the value of a custom Lua field attached to this Region." "\r\n"
	"import LuaValueList* GetLuaField(this Region*, String fieldName);" "\r\n"
	"/// Set the value of a custom Lua field attached to this Region." "\r\n"
	"import void SetLuaField(this Region*, String fieldName, LuaValueList* newValue);" "\r\n"
	"/// Get a read-only LuaValueList containing this Dialog." "\r\n"
	"import LuaValueList* AsLuaValue(this Dialog*);" "\r\n"
	"/// Attempt to call a custom Lua method attached to this Dialog." "\r\n"
	"import LuaValueList* LuaMethod(this Dialog*, String methodName, LuaValueList* params = 0, LuaCallMode = eLuaUnprotectedMode);" "\r\n"
	"/// Get the value of a custom Lua field attached to this Dialog." "\r\n"
	"import LuaValueList* GetLuaField(this Dialog*, String fieldName);" "\r\n"
	"/// Set the value of a custom Lua field attached to this Dialog." "\r\n"
	"import void SetLuaField(this Dialog*, String fieldName, LuaValueList* newValue);" "\r\n"
	"/// Get a read-only LuaValueList containing this DateTime." "\r\n"
	"import LuaValueList* AsLuaValue(this DateTime*);" "\r\n"
	"/// Attempt to call a custom Lua method attached to this DateTime." "\r\n"
	"import LuaValueList* LuaMethod(this DateTime*, String methodName, LuaValueList* params = 0, LuaCallMode = eLuaUnprotectedMode);" "\r\n"
	"#ifver 3.2" "\r\n"
	"/// Get a read-only LuaValueList containing this AudioChannel." "\r\n"
	"import LuaValueList* AsLuaValue(this AudioChannel*);" "\r\n"
	"/// Attempt to call a custom Lua method attached to this AudioChannel." "\r\n"
	"import LuaValueList* LuaMethod(this AudioChannel*, String methodName, LuaValueList* params = 0, LuaCallMode = eLuaUnprotectedMode);" "\r\n"
	"#endif" "\r\n"
	"#ifver 3.2" "\r\n"
	"/// Get a read-only LuaValueList containing this AudioClip." "\r\n"
	"import LuaValueList* AsLuaValue(this AudioClip*);" "\r\n"
	"/// Attempt to call a custom Lua method attached to this AudioClip." "\r\n"
	"import LuaValueList* LuaMethod(this AudioClip*, String methodName, LuaValueList* params = 0, LuaCallMode = eLuaUnprotectedMode);" "\r\n"
	"/// Get the value of a custom Lua field attached to this AudioClip." "\r\n"
	"import LuaValueList* GetLuaField(this AudioClip*, String fieldName);" "\r\n"
	"/// Set the value of a custom Lua field attached to this AudioClip." "\r\n"
	"import void SetLuaField(this AudioClip*, String fieldName, LuaValueList* newValue);" "\r\n"
	"#endif" "\r\n"
	"/// Get a read-only LuaValueList containing this Object." "\r\n"
	"import LuaValueList* AsLuaValue(this Object*);" "\r\n"
	"/// Attempt to call a custom Lua method attached to this Object." "\r\n"
	"import LuaValueList* LuaMethod(this Object*, String methodName, LuaValueList* params = 0, LuaCallMode = eLuaUnprotectedMode);" "\r\n"
	"/// Get the value of a custom Lua field attached to this Object." "\r\n"
	"import LuaValueList* GetLuaField(this Object*, String fieldName);" "\r\n"
	"/// Set the value of a custom Lua field attached to this Object." "\r\n"
	"import void SetLuaField(this Object*, String fieldName, LuaValueList* newValue);" "\r\n"
	"/// Get a read-only LuaValueList containing this Character." "\r\n"
	"import LuaValueList* AsLuaValue(this Character*);" "\r\n"
	"/// Attempt to call a custom Lua method attached to this Character." "\r\n"
	"import LuaValueList* LuaMethod(this Character*, String methodName, LuaValueList* params = 0, LuaCallMode = eLuaUnprotectedMode);" "\r\n"
	"/// Get the value of a custom Lua field attached to this Character." "\r\n"
	"import LuaValueList* GetLuaField(this Character*, String fieldName);" "\r\n"
	"/// Set the value of a custom Lua field attached to this Character." "\r\n"
	"import void SetLuaField(this Character*, String fieldName, LuaValueList* newValue);" "\r\n"
