
// LuaValueList members
	"/// Gets/sets values from the list as ViewFrames." "\r\n"
	"import attribute ViewFrame* AsViewFrames[]; // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Gets/sets values from the list as DrawingSurfaces." "\r\n"
	"import attribute DrawingSurface* AsDrawingSurfaces[]; // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Gets/sets values from the list as Files." "\r\n"
	"import attribute File* AsFiles[]; // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Gets/sets values from the list as InventoryItems." "\r\n"
	"import attribute InventoryItem* AsInventoryItems[]; // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Gets/sets values from the list as Overlays." "\r\n"
	"import attribute Overlay* AsOverlays[]; // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Gets/sets values from the list as DynamicSprites." "\r\n"
	"import attribute DynamicSprite* AsDynamicSprites[]; // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Gets/sets values from the list as GUIControls." "\r\n"
	"import attribute GUIControl* AsGUIControls[]; // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Gets/sets values from the list as Labels." "\r\n"
	"import attribute Label* AsLabels[]; // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Gets/sets values from the list as Buttons." "\r\n"
	"import attribute Button* AsButtons[]; // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Gets/sets values from the list as Sliders." "\r\n"
	"import attribute Slider* AsSliders[]; // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Gets/sets values from the list as TextBoxes." "\r\n"
	"import attribute TextBox* AsTextBoxes[]; // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Gets/sets values from the list as InvWindows." "\r\n"
	"import attribute InvWindow* AsInvWindows[]; // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Gets/sets values from the list as ListBoxes." "\r\n"
	"import attribute ListBox* AsListBoxes[]; // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Gets/sets values from the list as GUIs." "\r\n"
	"import attribute GUI* AsGUIs[]; // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Gets/sets values from the list as Hotspots." "\r\n"
	"import attribute Hotspot* AsHotspots[]; // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Gets/sets values from the list as Regions." "\r\n"
	"import attribute Region* AsRegions[]; // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Gets/sets values from the list as Dialogs." "\r\n"
	"import attribute Dialog* AsDialogs[]; // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Gets/sets values from the list as DateTimes." "\r\n"
	"import attribute DateTime* AsDateTimes[]; // $AUTOCOMPLETEIGNORE$" "\r\n"
	"#ifver 3.2" "\r\n"
	"/// Gets/sets values from the list as AudioChannels." "\r\n"
	"import attribute AudioChannel* AsAudioChannels[]; // $AUTOCOMPLETEIGNORE$" "\r\n"
	"#endif" "\r\n"
	"#ifver 3.2" "\r\n"
	"/// Gets/sets values from the list as AudioClips." "\r\n"
	"import attribute AudioClip* AsAudioClips[]; // $AUTOCOMPLETEIGNORE$" "\r\n"
	"#endif" "\r\n"
	"/// Gets/sets values from the list as Objects." "\r\n"
	"import attribute Object* AsObjects[]; // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Gets/sets values from the list as Characters." "\r\n"
	"import attribute Character* AsCharacters[]; // $AUTOCOMPLETEIGNORE$" "\r\n"
