// Lua struct members
	"/// Extracts a ViewFrame from a LuaValueList." "\r\n"
	"import static ViewFrame* ToViewFrame(LuaValueList* value, int pos = 1); // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Extracts a DrawingSurface from a LuaValueList." "\r\n"
	"import static DrawingSurface* ToDrawingSurface(LuaValueList* value, int pos = 1); // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Extracts a File from a LuaValueList." "\r\n"
	"import static File* ToFile(LuaValueList* value, int pos = 1); // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Extracts a InventoryItem from a LuaValueList." "\r\n"
	"import static InventoryItem* ToInventoryItem(LuaValueList* value, int pos = 1); // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Extracts a Overlay from a LuaValueList." "\r\n"
	"import static Overlay* ToOverlay(LuaValueList* value, int pos = 1); // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Extracts a DynamicSprite from a LuaValueList." "\r\n"
	"import static DynamicSprite* ToDynamicSprite(LuaValueList* value, int pos = 1); // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Extracts a GUIControl from a LuaValueList." "\r\n"
	"import static GUIControl* ToGUIControl(LuaValueList* value, int pos = 1); // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Extracts a Label from a LuaValueList." "\r\n"
	"import static Label* ToLabel(LuaValueList* value, int pos = 1); // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Extracts a Button from a LuaValueList." "\r\n"
	"import static Button* ToButton(LuaValueList* value, int pos = 1); // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Extracts a Slider from a LuaValueList." "\r\n"
	"import static Slider* ToSlider(LuaValueList* value, int pos = 1); // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Extracts a TextBox from a LuaValueList." "\r\n"
	"import static TextBox* ToTextBox(LuaValueList* value, int pos = 1); // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Extracts a InvWindow from a LuaValueList." "\r\n"
	"import static InvWindow* ToInvWindow(LuaValueList* value, int pos = 1); // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Extracts a ListBox from a LuaValueList." "\r\n"
	"import static ListBox* ToListBox(LuaValueList* value, int pos = 1); // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Extracts a GUI from a LuaValueList." "\r\n"
	"import static GUI* ToGUI(LuaValueList* value, int pos = 1); // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Extracts a Hotspot from a LuaValueList." "\r\n"
	"import static Hotspot* ToHotspot(LuaValueList* value, int pos = 1); // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Extracts a Region from a LuaValueList." "\r\n"
	"import static Region* ToRegion(LuaValueList* value, int pos = 1); // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Extracts a Dialog from a LuaValueList." "\r\n"
	"import static Dialog* ToDialog(LuaValueList* value, int pos = 1); // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Extracts a DateTime from a LuaValueList." "\r\n"
	"import static DateTime* ToDateTime(LuaValueList* value, int pos = 1); // $AUTOCOMPLETEIGNORE$" "\r\n"
	"#ifver 3.2" "\r\n"
	"/// Extracts a AudioChannel from a LuaValueList." "\r\n"
	"import static AudioChannel* ToAudioChannel(LuaValueList* value, int pos = 1); // $AUTOCOMPLETEIGNORE$" "\r\n"
	"#endif" "\r\n"
	"#ifver 3.2" "\r\n"
	"/// Extracts a AudioClip from a LuaValueList." "\r\n"
	"import static AudioClip* ToAudioClip(LuaValueList* value, int pos = 1); // $AUTOCOMPLETEIGNORE$" "\r\n"
	"#endif" "\r\n"
	"/// Extracts a Object from a LuaValueList." "\r\n"
	"import static Object* ToObject(LuaValueList* value, int pos = 1); // $AUTOCOMPLETEIGNORE$" "\r\n"
	"/// Extracts a Character from a LuaValueList." "\r\n"
	"import static Character* ToCharacter(LuaValueList* value, int pos = 1); // $AUTOCOMPLETEIGNORE$" "\r\n"
